const SZENARIEN = [
  {
    "id": "zweitstimme",
    "titel": "Zweitstimmen",
    "untertitel": "Hier findest du die Wahlergebnisse in der klassischen Ansicht",
    "beschreibung": "In der klassischen Ansicht sind die Wahlbezirke in der Farbe der meistgewählten Partei eingefärbt.<br><br><b>Weitere Analysen:</b> Zum Beispiel die <a href=\"#erststimme\">Erststimmen</a>, <a href=\"#kleinparteien\">Kleinparteien</a>, <a href=\"#wechselwaehler\">Wechsel&shy;wähler*innen</a>, <a href=\"#gewinner\">größter Gewinner</a>, <a href=\"#verlierer\">größter Verlierer</a> und eine Analyse zu <a href=\"#erst-vs-zweit\">Erststimmen vs. Zweitstimmen</a>. Klick dich einfach mit den Pfeilen durch! :)",
    "getAnalyse": getAnalyseForWahlergebnisse,
  },
  {
    "id": "erststimme",
    "titel": "Erststimmen",
    "untertitel": "Übersicht der gewählten Kandidaten",
    "beschreibung": "Die Wahlbezirke sind in der Farbe der Partei des meistgewählten Kandidaten gefärbt.",
    "getAnalyse": getAnalyseForErststimmen,
  },
  {
    "id": "wechselwaehler",
    "titel": "Wechsel&shy;wähler*innen",
    "untertitel": "Welche Wahlbezirke haben die Farbe gewechselt?",
    "beschreibung": "Die Wahlbezirke, in denen die meistgewählte Partei im Vergleich zur Bundestagswahl 2013 gewechselt ist, sind hier hervorgehoben.",
    "getAnalyse": getAnalyseForWechselwaehler,
  },
  {
    "id": "erst-vs-zweit",
    "titel": "Erst- vs. Zweitstimmen",
    "untertitel": "Wo unterscheiden sich die Sieger?",
    "beschreibung": "Hervorgehoben sind die Wahlbezirke, in denen sich die meistgewählte Partei von der Partei des meistegwählten Kandidaten unterscheiden.",
    "getAnalyse": getAnalyseForErstVsZweit,
  },
  {
    "id": "gewinner",
    "titel": "Größter Gewinner",
    "untertitel": "Welche Partei hat am meisten zugelegt?",
    "beschreibung": "Die Wahlbezirke sind in der Farbe der Partei eingefärbt, die im Vergleich zur letzten Bundestagswahl relativ betrachtet die größten Stimmgewinne hat.",
    "getAnalyse": getAnalyseGroessterGewinner,
  },
  {
    "id": "verlierer",
    "titel": "Größter Verlierer",
    "untertitel": "Welche Partei hat am meisten verloren?",
    "beschreibung": "Die Wahlbezirke sind in der Farbe der Partei eingefärbt, die im Vergleich zur letzten Bundestagswahl relativ betrachtet die größten Stimmverluste hat.",
    "getAnalyse": getAnalyseGroessterVerlierer,
  },
  {
    "id": "ungueltig",
    "titel": "Ungültige Stimmen",
    "untertitel": "Wie viele ungültige Stimmen gibt es in den jeweiligen Wahlbezirken?",
    "beschreibung": "Je dunkler die Farbe des Wahlbezirks ist, desto mehr ungültige Erst- und Zweitstimmen gab es.",
    "getAnalyse": getAnalyseForUngueltigeStimmen,
  },
  {
    "id": "kleinster-abstand",
    "titel": "Kleinster Abstand",
    "untertitel": "In welchen Wahlbezirken war das Ergebnis am knappsten?",
    "beschreibung": "Gezeigt werden die Wahlbezirke, in denen der Abstand zwischen dem Erst- und Zweitplatzierten am geringsten ist. Ausgewertet werden die Zweitstimmen der Parteien in Relation zur Gesamtzahl der Wähler.",
    "getAnalyse": getAnalyseForKleinsterAbstand,
  },
  {
    "id": "kleinparteien",
    "titel": "Größte Kleine",
    "untertitel": "Die Zweitstimmen&shy;ergebnisse ohne CDU und SPD",
    "beschreibung": "Hier haben wir die großen Parteien, also CDU und SPD, aus der Ansicht verbannt. So siehst du nur die \"Kleinparteien\", und wo sie abgestaubt haben.",
    "getAnalyse": getAnalyseForKleinparteien,
  },
]
